[package]
edition = "2021"
name = "bootme"
version = "0.1.0"
publish = false

[workspace]
members = [
  "contracts/*",
  "./util"
]
# exclude = ["util", "bootme"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[dev-dependencies]
anyhow = "1.0"
lazy-static-include = "3.1.2"
near-sdk = "4.0.0-pre.8"
near-units = "0.2.0"
proc-macro2 = { version = "1.0.36", features = ["span-locations"] }
serde_json = "1.0"
tokio = { version = "1.14", features = ["full"] }
workspaces = "0.2.1"

[package.metadata.hackerman.stash.dev-dependencies]
proc-macro2 = false
