[package]
edition = "2021"
name = "bootloader"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# near-units = "0.2.0"
contract-utils = {path = "../../util"}

[dev-dependencies]
witgen = "0.11.0"
