[package]
edition = "2021"
name = "bootloader"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# near-units = "0.2.0"
near-components-core = {path = "../../components/core"}
near-components = {path = "../.."}


[features]
default = ["near-components-core/wee_alloc"]
testnet = []
