[package]
edition = "2021"
name = "bootloader"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# near-units = "0.2.0"
near-components = {path = "../..", features = ["wee_alloc"]}

[dev-dependencies]
witgen = "0.11.0"

[features]
testnet = []
