[package]
authors = ["Willem Wyndham <willem@near.org>"]
edition = "2021"
name = "contract-registry"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-components = { path = "../..", features = ["publish", "wee_alloc"]}