[package]
edition = "2021"
name = "status-message"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-components = {path = "../..", features = ["wee_alloc"]}
near-components-core = {path = "../../components/core"}